---
dist: trusty
sudo: required
services:
  - docker
language: go

env:
  global: GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code UnitTest"
      script:
        - make test
    - go: "1.13.x"
      name: "Website"
      script:
        - make website-test

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh

branches:
  only:
    - master